image: python:3.8

stages:
  - build
  - deploy

before_script:
  # Install necessary dependencies
  - pip install packaging
  - wget https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_0.111.3_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar -xvf hugo.tar.gz
  - mv hugo /usr/local/bin/hugo

build:
  stage: build
  script:
    # Run the build script
    - python3 ./build.py
  artifacts:
    paths:
      - data

pages:
  stage: deploy
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - main
